Creating test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Found 45 test(s).
Operations to perform:
  Synchronize unmigrated apps: messages, rest_framework, staticfiles
  Apply all migrations: address, admin, auth, authtoken, contenttypes, courses, sessions, users
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying address.0001_initial... OK
  Applying users.0001_initial... OK
  Applying address.0002_initial... OK
  Applying address.0003_remove_address_user... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying courses.0001_initial... OK
  Applying courses.0002_course_instructor_course_students... OK
  Applying sessions.0001_initial... OK
System check identified no issues (0 silenced).
test_duplicate_email_user_creation_422 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_instructor_user_creation_201 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_list_users_by_instructor_200 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_list_users_by_student_403 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_list_users_with_no_token_401 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_login_success_200 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_login_with_invalid_credentials_401 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_login_with_wrong_fields_400 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_student_user_creation_201 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_wrong_data_user_creation_400 (test_api.TestAccountsRoutesWithoutAuthentication) ... ok
test_address_creation_200 (test_api.TestAddress) ... FAIL
test_address_creation_already_exists_200 (test_api.TestAddress) ... ok
test_address_creation_wrong_data_400 (test_api.TestAddress) ... FAIL
test_delete_course_by_instructor_204 (test_api.TestCourseDelete) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:24:52.756091) while time zone support is active.
  warnings.warn(
FAIL
test_delete_course_by_no_user_401 (test_api.TestCourseDelete) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:24:53.550859) while time zone support is active.
  warnings.warn(
ok
test_delete_course_by_student_403 (test_api.TestCourseDelete) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:24:54.151596) while time zone support is active.
  warnings.warn(
ok
test_delete_course_with_invalid_course_id_404 (test_api.TestCourseDelete) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:24:54.935941) while time zone support is active.
  warnings.warn(
FAIL
test_course_creation_by_instructor_201 (test_api.TestCoursesCreation) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:24:55.730851) while time zone support is active.
  warnings.warn(
ok
test_course_creation_by_no_user_401 (test_api.TestCoursesCreation) ... ok
test_course_creation_by_student_403 (test_api.TestCoursesCreation) ... ok
test_course_creation_duplicate_name_422 (test_api.TestCoursesCreation) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:24:57.309065) while time zone support is active.
  warnings.warn(
ok
test_course_creation_wrong_data_400 (test_api.TestCoursesCreation) ... ok
test_list_courses_200 (test_api.TestCoursesCreation) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:24:58.540674) while time zone support is active.
  warnings.warn(
ok
test_retrieve_invalid_course_404 (test_api.TestCoursesCreation) ... ok
test_retrieve_valid_course_200 (test_api.TestCoursesCreation) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:24:59.551424) while time zone support is active.
  warnings.warn(
FAIL
test_register_instructor_course_by_instructor_200 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:00.330479) while time zone support is active.
  warnings.warn(
ERROR
test_register_instructor_course_by_no_user_401 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:01.302826) while time zone support is active.
  warnings.warn(
ERROR
test_register_instructor_course_by_student_403 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:02.103289) while time zone support is active.
  warnings.warn(
ERROR
test_register_instructor_course_with_invalid_id_404 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:03.069688) while time zone support is active.
  warnings.warn(
ERROR
test_register_instructor_course_with_student_id_422 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:04.026591) while time zone support is active.
  warnings.warn(
ERROR
test_register_instructor_course_with_wrong_field_400 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:04.997295) while time zone support is active.
  warnings.warn(
ERROR
test_register_instructor_course_wrong_courseId_404 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:05.956394) while time zone support is active.
  warnings.warn(
ERROR
test_register_students_course_by_intructor_200 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:06.919377) while time zone support is active.
  warnings.warn(
ERROR
test_register_students_course_by_no_user_401 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:07.877252) while time zone support is active.
  warnings.warn(
ERROR
test_register_students_course_by_student_403 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:08.652569) while time zone support is active.
  warnings.warn(
ERROR
test_register_students_course_invalid_course_id_404 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:09.635916) while time zone support is active.
  warnings.warn(
ERROR
test_register_students_course_with_instructor_id_422 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:10.589241) while time zone support is active.
  warnings.warn(
ERROR
test_register_students_course_with_invalid_student_id_404 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:11.549500) while time zone support is active.
  warnings.warn(
ERROR
test_register_students_course_with_wrong_field_400 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:12.506124) while time zone support is active.
  warnings.warn(
ERROR
test_register_students_course_with_wrong_field_type_400 (test_api.TestCoursesRegister) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:13.468505) while time zone support is active.
  warnings.warn(
ERROR
test_update_course_by_instructor_200 (test_api.TestCoursesUpdate) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:14.056350) while time zone support is active.
  warnings.warn(
FAIL
test_update_course_by_no_user_401 (test_api.TestCoursesUpdate) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:14.831044) while time zone support is active.
  warnings.warn(
ok
test_update_course_by_student_403 (test_api.TestCoursesUpdate) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:15.461579) while time zone support is active.
  warnings.warn(
ok
test_update_course_with_conflict_422 (test_api.TestCoursesUpdate) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:16.247059) while time zone support is active.
  warnings.warn(
/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:16.632388) while time zone support is active.
  warnings.warn(
FAIL
test_update_invalid_course_404 (test_api.TestCoursesUpdate) ... /home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1534: RuntimeWarning: DateTimeField Course.created_at received a naive datetime (2022-03-20 01:25:17.040686) while time zone support is active.
  warnings.warn(
FAIL

======================================================================
ERROR: test_register_instructor_course_by_instructor_200 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 630, in test_register_instructor_course_by_instructor_200
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_by_no_user_401 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 707, in test_register_instructor_course_by_no_user_401
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_by_student_403 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 687, in test_register_instructor_course_by_student_403
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_with_invalid_id_404 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 776, in test_register_instructor_course_with_invalid_id_404
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_with_student_id_422 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 751, in test_register_instructor_course_with_student_id_422
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_with_wrong_field_400 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 801, in test_register_instructor_course_with_wrong_field_400
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_instructor_course_wrong_courseId_404 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 731, in test_register_instructor_course_wrong_courseId_404
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_by_intructor_200 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 829, in test_register_students_course_by_intructor_200
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_by_no_user_401 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 894, in test_register_students_course_by_no_user_401
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_by_student_403 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 872, in test_register_students_course_by_student_403
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_invalid_course_id_404 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 919, in test_register_students_course_invalid_course_id_404
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_with_instructor_id_422 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 969, in test_register_students_course_with_instructor_id_422
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_with_invalid_student_id_404 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 944, in test_register_students_course_with_invalid_student_id_404
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_with_wrong_field_400 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 994, in test_register_students_course_with_wrong_field_400
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
ERROR: test_register_students_course_with_wrong_field_type_400 (test_api.TestCoursesRegister)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 1019, in test_register_students_course_with_wrong_field_type_400
    output = response.json()
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/venv/lib/python3.9/site-packages/django/test/client.py", line 748, in _parse_json
    raise ValueError(
ValueError: Content-Type header is "text/html", not "application/json"

======================================================================
FAIL: test_address_creation_200 (test_api.TestAddress)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 1228, in test_address_creation_200
    self.assertIn("house_number", output)
AssertionError: 'house_number' not found in {'uuid': 'bcf3109e-4c89-4433-904e-8254038e7f79', 'street': 'Rua das Orquídeas', 'city': 'Taubaté', 'state': 'SP', 'zip_code': '86990-000', 'country': 'Brasil', 'users': [{'uuid': 'ea6cb391-f5e5-432b-8324-fc3595fd1f74', 'first_name': 'Student', 'last_name': 'Kenzie', 'email': 'student@kenzie.com.br', 'is_admin': False}]}

======================================================================
FAIL: test_address_creation_wrong_data_400 (test_api.TestAddress)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 1278, in test_address_creation_wrong_data_400
    self.assertIn("house_number", output)
AssertionError: 'house_number' not found in {'zip_code': ['This field is required.']}

======================================================================
FAIL: test_delete_course_by_instructor_204 (test_api.TestCourseDelete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 1088, in test_delete_course_by_instructor_204
    self.assertEqual(response.status_code, 204)
AssertionError: 403 != 204

======================================================================
FAIL: test_delete_course_with_invalid_course_id_404 (test_api.TestCourseDelete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 1140, in test_delete_course_with_invalid_course_id_404
    self.assertEqual(response.status_code, 404)
AssertionError: 403 != 404

======================================================================
FAIL: test_retrieve_valid_course_200 (test_api.TestCoursesCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 366, in test_retrieve_valid_course_200
    self.assertEqual(output, course)
AssertionError: {'uui[76 chars]09:00:00', 'created_at': '2022-03-20T01:24:59.[88 chars]: []} != {'uui[76 chars]09:00', 'created_at': '2022-03-20T01:24:59.551[85 chars]: []}
  {'created_at': '2022-03-20T01:24:59.551424Z',
-  'demo_time': '09:00:00',
?                     ---

+  'demo_time': '09:00',
   'instructor': None,
   'link_repo': 'https://gitlab.com/django_demos',
   'name': 'Django',
   'students': [],
   'uuid': '1878a543-95b4-4c08-9cc2-9254dec88c69'}

======================================================================
FAIL: test_update_course_by_instructor_200 (test_api.TestCoursesUpdate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 448, in test_update_course_by_instructor_200
    self.assertEqual(response.status_code, 200)
AssertionError: 403 != 200

======================================================================
FAIL: test_update_course_with_conflict_422 (test_api.TestCoursesUpdate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 524, in test_update_course_with_conflict_422
    self.assertEqual(response.status_code, 422)
AssertionError: 403 != 422

======================================================================
FAIL: test_update_invalid_course_404 (test_api.TestCoursesUpdate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keila/q4/entregas/parte2-django/e10-kanvas/test_api.py", line 499, in test_update_invalid_course_404
    self.assertEqual(response.status_code, 404)
AssertionError: 403 != 404

----------------------------------------------------------------------
Ran 45 tests in 30.622s

FAILED (failures=8, errors=15)
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
